### ISSUE TITLE
win11 jdk11 加载不了 nuclei-templates

### ISSUE THREAD

**Issue by luck-ying** [Yong-An-Dang/nuclei-plus#29]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/58284151/f6a69b93-ef04-4c04-9143-074f1b8ab4d6)

2024/01/10 07:56:18,910 DEBUG [SwingWorker-pool-1-thread-1] (StringTargetPanel.java:158:initSearchDialogs) - initSearchDialogs
2024/01/10 07:56:19,077 DEBUG [SwingWorker-pool-1-thread-1] (ConfigNucleiPanel.java:139:initSearchDialogs) - initSearchDialogs
2024/01/10 07:56:19,173 DEBUG [SwingWorker-pool-1-thread-1] (ConfigTemplatePanel.java:115:initSearchDialogs) - initSearchDialogs
2024/01/10 07:56:19,255 DEBUG [SwingWorker-pool-1-thread-1] (ConfigWorkflowPanel.java:114:initSearchDialogs) - initSearchDialogs
2024/01/10 07:56:19,547 DEBUG [SwingWorker-pool-1-thread-1] (TerminalPanel.java:711:establishFontMetrics) - charHeight=23->21, descent=4->3
2024/01/10 07:56:19,556 DEBUG [SwingWorker-pool-1-thread-1] (ConsolePanel.java:71:createTtyConnector) - {USERDOMAIN_ROAMINGPROFILE=YING, WT_SESSION=61b17dd6-5fb5-4388-a5f4-c4f68dac71de, LOCALAPPDATA=C:\Users\75347\AppData\Local, PROCESSOR_LEVEL=25, IntelliJ IDEA=d:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5\bin;, USERDOMAIN=YING, LOGONSERVER=\\YING, STARSHIP_SESSION_KEY=dQYEthV5q9wKRzGy, JAVA_HOME=C:\Program Files\Java\jdk-11.0.6, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, VIRTUAL_ENV_DISABLE_PROMPT=1, PSModulePath=C:\Users\75347\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules, SystemDrive=C:, asl.log=Destination=file, WT_PROFILE_ID={574e775e-4f2a-5b96-ac1e-a2962a402336}, OneDrive=C:\Users\75347\OneDrive, APPDATA=C:\Users\75347\AppData\Roaming, STARSHIP_SHELL=pwsh, USERNAME=ying, ProgramFiles(x86)=C:\Program Files (x86), CommonProgramFiles=C:\Program Files\Common Files, Path=C:\Program Files\PowerShell\7;C:\Program Files\Java\jdk-11.0.6\bin\;C:\Users\75347\AppData\Roaming\Python\Python310\Scripts;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\ProgramData\Oracle\Java\javapath;D:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Bandizip;C:\Program Files\PowerShell\7\;D:\Program Files\Bandizip\Bandizip;C:\Program Files\starship\bin\;C:\Users\75347\AppData\Local\Microsoft\WindowsApps;D:\Program Files\Microsoft VS Code\bin;d:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5\bin;C:\Users\75347\.nuclei-plus\bin, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL, DriverData=C:\Windows\System32\Drivers\DriverData, OS=Windows_NT, COMPUTERNAME=YING, PROCESSOR_REVISION=7401, CLASSPATH=.;C:\Program Files\Java\jdk-11.0.6\lib;C:\Program Files\Java\jdk-11.0.6\lib\dt.jar;C:\Program Files\Java\jdk-11.0.6\lib\tools.jar;, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\Windows\system32\cmd.exe, ProgramData=C:\ProgramData, ProgramW6432=C:\Program Files, HOMEPATH=\Users\75347, SystemRoot=C:\Windows, TEMP=C:\Users\75347\AppData\Local\Temp, HOMEDRIVE=C:, PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD, USERPROFILE=C:\Users\75347, TMP=C:\Users\75347\AppData\Local\Temp, WSLENV=WT_SESSION::WT_PROFILE_ID, POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Home China, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, NUMBER_OF_PROCESSORS=16, windir=C:\Windows}
2024/01/10 07:56:20,050 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:94:doInit) - Found C:\Users\75347\AppData\Local\Temp\pty4j-win-x86-64-16377485843914619280 in 0 ms
2024/01/10 07:56:20,054 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:101:doInit) - Listed files in 9 ms
2024/01/10 07:56:20,055 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:111:doInit) - Checked upToDate in 9 ms
2024/01/10 07:56:20,055 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:118:doInit) - Cleared directory in 9 ms
2024/01/10 07:56:20,068 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:124:doInit) - Copied [resources/com/pty4j/native/win/x86-64/winpty-agent.exe, resources/com/pty4j/native/win/x86-64/win-helper.dll, resources/com/pty4j/native/win/x86-64/winpty.dll, resources/com/pty4j/native/win/x86-64/cyglaunch.exe] in 22 ms
2024/01/10 07:56:20,069 INFO [SwingWorker-pool-1-thread-1] (ExtractedNative.java:128:doInit) - Extracted pty4j native in 23 ms
2024/01/10 07:56:20,097 INFO [SwingWorker-pool-1-thread-1] (WindowsVersion.java:27:getVersion) - Windows version: 10.0.22621
2024/01/10 07:56:20,296 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0m, raw: ESC[0m)
2024/01/10 07:56:20,297 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 07:56:20,331 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 07:56:20,331 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?25l, raw: ESC[?25l)
2024/01/10 07:56:20,335 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode CursorVisible enabled = false
2024/01/10 07:56:20,336 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 07:56:20,336 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 07:56:20,336 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 07:56:20,336 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?25h, raw: ESC[?25h)
2024/01/10 07:56:20,336 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode CursorVisible enabled = true
2024/01/10 07:56:20,796 DEBUG [AWT-EventQueue-0] (StartupFrame.java:249:done) - 已执行：NucleiApp.createGUI();
2024/01/10 07:56:20,809 DEBUG [AWT-EventQueue-0] (StartupFrame.java:251:done) - 已执行：StartupFrame.this.dispose();
Exception in thread "Thread-0" while scanning a simple key
 in 'reader', line 15, column 1:
    POST /eis/service/api.aspx?actio ...
    ^
could not find expected ':'
 in 'reader', line 16, column 1:
    Host: {{Hostname}}
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:586)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486)
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getMapFromYaml(CommonUtil.java:157)
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getTemplateInfoFromPath(CommonUtil.java:199)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:538)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:533)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.walkFiles(TemplatesPanel.java:533)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:521)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$2(TemplatesPanel.java:430)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-2" while scanning a simple key
 in 'reader', line 15, column 1:
    POST /eis/service/api.aspx?actio ...
    ^
could not find expected ':'
 in 'reader', line 16, column 1:
    Host: {{Hostname}}
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:586)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486)
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getMapFromYaml(CommonUtil.java:157)
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getTemplateInfoFromPath(CommonUtil.java:199)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:538)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:533)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.walkFiles(TemplatesPanel.java:533)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:521)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$2(TemplatesPanel.java:430)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by luck-ying** [comment]
上面一个解决了 下面还有一个
2024/01/10 08:04:27,865 DEBUG [SwingWorker-pool-1-thread-1] (StringTargetPanel.java:158:initSearchDialogs) - initSearchDialogs
2024/01/10 08:04:28,039 DEBUG [SwingWorker-pool-1-thread-1] (ConfigNucleiPanel.java:139:initSearchDialogs) - initSearchDialogs
2024/01/10 08:04:28,137 DEBUG [SwingWorker-pool-1-thread-1] (ConfigTemplatePanel.java:115:initSearchDialogs) - initSearchDialogs
2024/01/10 08:04:28,223 DEBUG [SwingWorker-pool-1-thread-1] (ConfigWorkflowPanel.java:114:initSearchDialogs) - initSearchDialogs
2024/01/10 08:04:28,497 DEBUG [SwingWorker-pool-1-thread-1] (TerminalPanel.java:711:establishFontMetrics) - charHeight=23->21, descent=4->3
2024/01/10 08:04:28,506 DEBUG [SwingWorker-pool-1-thread-1] (ConsolePanel.java:71:createTtyConnector) - {USERDOMAIN_ROAMINGPROFILE=YING, WT_SESSION=61b17dd6-5fb5-4388-a5f4-c4f68dac71de, LOCALAPPDATA=C:\Users\75347\AppData\Local, PROCESSOR_LEVEL=25, IntelliJ IDEA=d:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5\bin;, USERDOMAIN=YING, LOGONSERVER=\\YING, STARSHIP_SESSION_KEY=dQYEthV5q9wKRzGy, JAVA_HOME=C:\Program Files\Java\jdk-11.0.6, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, VIRTUAL_ENV_DISABLE_PROMPT=1, PSModulePath=C:\Users\75347\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules, SystemDrive=C:, asl.log=Destination=file, WT_PROFILE_ID={574e775e-4f2a-5b96-ac1e-a2962a402336}, OneDrive=C:\Users\75347\OneDrive, APPDATA=C:\Users\75347\AppData\Roaming, STARSHIP_SHELL=pwsh, USERNAME=ying, ProgramFiles(x86)=C:\Program Files (x86), CommonProgramFiles=C:\Program Files\Common Files, Path=C:\Program Files\PowerShell\7;C:\Program Files\Java\jdk-11.0.6\bin\;C:\Users\75347\AppData\Roaming\Python\Python310\Scripts;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\ProgramData\Oracle\Java\javapath;D:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Bandizip;C:\Program Files\PowerShell\7\;D:\Program Files\Bandizip\Bandizip;C:\Program Files\starship\bin\;C:\Users\75347\AppData\Local\Microsoft\WindowsApps;D:\Program Files\Microsoft VS Code\bin;d:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5\bin;C:\Users\75347\.nuclei-plus\bin, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL, DriverData=C:\Windows\System32\Drivers\DriverData, OS=Windows_NT, COMPUTERNAME=YING, PROCESSOR_REVISION=7401, CLASSPATH=.;C:\Program Files\Java\jdk-11.0.6\lib;C:\Program Files\Java\jdk-11.0.6\lib\dt.jar;C:\Program Files\Java\jdk-11.0.6\lib\tools.jar;, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\Windows\system32\cmd.exe, ProgramData=C:\ProgramData, ProgramW6432=C:\Program Files, HOMEPATH=\Users\75347, SystemRoot=C:\Windows, TEMP=C:\Users\75347\AppData\Local\Temp, HOMEDRIVE=C:, PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD, USERPROFILE=C:\Users\75347, TMP=C:\Users\75347\AppData\Local\Temp, WSLENV=WT_SESSION::WT_PROFILE_ID, POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Home China, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, NUMBER_OF_PROCESSORS=16, windir=C:\Windows}
2024/01/10 08:04:28,983 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:94:doInit) - Found C:\Users\75347\AppData\Local\Temp\pty4j-win-x86-64-12736786644274641570 in 1 ms
2024/01/10 08:04:28,985 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:101:doInit) - Listed files in 6 ms
2024/01/10 08:04:28,986 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:111:doInit) - Checked upToDate in 7 ms
2024/01/10 08:04:28,988 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:118:doInit) - Cleared directory in 10 ms
2024/01/10 08:04:29,002 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:124:doInit) - Copied [resources/com/pty4j/native/win/x86-64/winpty-agent.exe, resources/com/pty4j/native/win/x86-64/win-helper.dll, resources/com/pty4j/native/win/x86-64/winpty.dll, resources/com/pty4j/native/win/x86-64/cyglaunch.exe] in 23 ms
2024/01/10 08:04:29,003 INFO [SwingWorker-pool-1-thread-1] (ExtractedNative.java:128:doInit) - Extracted pty4j native in 24 ms
2024/01/10 08:04:29,032 INFO [SwingWorker-pool-1-thread-1] (WindowsVersion.java:27:getVersion) - Windows version: 10.0.22621
2024/01/10 08:04:29,220 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0m, raw: ESC[0m)
2024/01/10 08:04:29,223 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 08:04:29,229 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 08:04:29,229 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?25l, raw: ESC[?25l)
2024/01/10 08:04:29,232 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode CursorVisible enabled = false
2024/01/10 08:04:29,232 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 08:04:29,232 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 08:04:29,233 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[0K, raw: ESC[0K)
2024/01/10 08:04:29,233 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?25h, raw: ESC[?25h)
2024/01/10 08:04:29,233 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode CursorVisible enabled = true
2024/01/10 08:04:29,660 DEBUG [AWT-EventQueue-0] (StartupFrame.java:249:done) - 已执行：NucleiApp.createGUI();
2024/01/10 08:04:29,669 DEBUG [AWT-EventQueue-0] (StartupFrame.java:251:done) - 已执行：StartupFrame.this.dispose();
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getTemplateInfoFromPath(CommonUtil.java:206)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:538)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:533)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.walkFiles(TemplatesPanel.java:533)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:521)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$2(TemplatesPanel.java:430)
        at java.base/java.lang.Thread.run(Thread.java:834)
2024/01/10 08:04:41,541 DEBUG [AWT-EventQueue-0] (NucleiApp.java:83:windowIconified) - 最小化窗口，Windows
Exception in thread "Thread-2" java.lang.NullPointerException
        at com.g3g4x5x6.nuclei.ultils.CommonUtil.getTemplateInfoFromPath(CommonUtil.java:206)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:538)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:533)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.walkFiles(TemplatesPanel.java:533)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:521)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$2(TemplatesPanel.java:430)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by G3G4X5X6** [comment]
模板格式不正确导致的问题，最新版已修复。
