### ISSUE TITLE
启动报错：目录创建失败

### ISSUE THREAD

**Issue by G3G4X5X6** [Yong-An-Dang/nuclei-plus#30]
```shell
E:\HackTools\nuclei-plus>jdk-11.0.0.2\bin\java.exe -jar nuclei-7.3.2.jar
2024/07/16 20:11:14,208 DEBUG [main] (CheckUtil.java:30:checkEnv) - 目录创建失败：
2024/07/16 20:11:21,019 DEBUG [SwingWorker-pool-1-thread-1] (StringTargetPanel.java:158:initSearchDialogs) - initSearchDialogs
2024/07/16 20:11:21,471 DEBUG [SwingWorker-pool-1-thread-1] (ConfigNucleiPanel.java:139:initSearchDialogs) - initSearchDialogs
2024/07/16 20:11:21,705 DEBUG [SwingWorker-pool-1-thread-1] (ConfigTemplatePanel.java:115:initSearchDialogs) - initSearchDialogs
2024/07/16 20:11:21,799 DEBUG [SwingWorker-pool-1-thread-1] (ConfigWorkflowPanel.java:114:initSearchDialogs) - initSearchDialogs
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
        at com.g3g4x5x6.StartupFrame$6.done(StartupFrame.java:244)
        at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError
        at com.g3g4x5x6.nuclei.NucleiFrame.<init>(NucleiFrame.java:50)
        at com.g3g4x5x6.NucleiApp.createGUI(NucleiApp.java:68)
        at com.g3g4x5x6.StartupFrame$6.doInBackground(StartupFrame.java:235)
        at com.g3g4x5x6.StartupFrame$6.doInBackground(StartupFrame.java:229)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.g3g4x5x6.nuclei.ultils.NucleiConfig.getProperty(NucleiConfig.java:56)
        at com.g3g4x5x6.nuclei.panel.tab.RunningPanel.<clinit>(RunningPanel.java:19)
        ... 10 more
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.g3g4x5x6.nuclei.ultils.NucleiConfig.getProperty(NucleiConfig.java:56)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:536)
        at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$5(TemplatesPanel.java:463)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by G3G4X5X6** [comment]
v7.3.5 已修复。
