### ISSUE TITLE
【BUG】第一次启动找不到程序配置文件（第二次即可正常启动）

### ISSUE THREAD

**Issue by G3G4X5X6** [Yong-An-Dang/nuclei-plus#6]
### 操作系统
ubuntu22.04

### 异常
```
java.nio.file.NoSuchFileException: /home/dev/.nuclei-plus/config/nuclei.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.copy(Files.java:3067)
	at com.g3g4x5x6.nuclei.ultils.NucleiConfig.loadProperties(NucleiConfig.java:28)
	at com.g3g4x5x6.nuclei.ultils.NucleiConfig.<clinit>(NucleiConfig.java:15)
	at com.g3g4x5x6.nuclei.ultils.CheckUtil.checkEnv(CheckUtil.java:14)
	at com.g3g4x5x6.NucleiApp.main(NucleiApp.java:27)
Failed to initialize LaF
Exception in thread "main" java.lang.NullPointerException
	at com.g3g4x5x6.nuclei.ultils.NucleiConfig.getProperty(NucleiConfig.java:52)
	at com.g3g4x5x6.StartupFrame.<init>(StartupFrame.java:38)
	at com.g3g4x5x6.StartupFrame.setup(StartupFrame.java:223)
	at com.g3g4x5x6.NucleiApp.main(NucleiApp.java:33)

```

**Comment by G3G4X5X6** [comment]
已修复
